imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MyAlphabusBundle/Resources/config/services.yml" }
    - { resource: "@MyUserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    #translator: { fallbacks: [ "en" ] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
# FOS UserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: My\UserBundle\Entity\User
# FOS Easy Bundle
easy_admin:
    site_name: 'AlphaBus Tunisie'
    design:
        brand_color: 'rgb(176,33,26)'
    list:
        max_results: 30
    formats:
        date:     'd-m-Y'
    entities:
            Chassis:
               class: My\AlphabusBundle\Entity\Chassis
               list:
                  fields: ['nchassis','typechassis','datereception','controler']
               form:
                  fields: ['nchassis','typechassis','datereception','controler']

            Clients:
               class: My\AlphabusBundle\Entity\Clients
               list:
                  fields: ['nclients','nom','prenom','societe','telephone','email']
               form:
                   fields: ['nclients','nom','prenom','societe','adresse','codepostal','ville','telephone','email']
            User:
               class: My\UserBundle\Entity\User

            Affectation:
               class:  My\AlphabusBundle\Entity\Affectation
               list:
                  fields: ['seriealpha','dateaffectation','nclients','chassis']
             
            Post:
               class: My\AlphabusBundle\Entity\Post
               list: 
                  fields: ['etat','titre','proprietaire','remarques','date']
               form:
                   fields: ['etat','titre','proprietaire','remarques','date']
                
                 
                              