<?php

namespace My\ControlerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * documentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class documentationRepository extends EntityRepository
{
}
