<?php

namespace My\AlphabusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PeintureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeintureRepository extends EntityRepository
{
}
