<?php

namespace My\AlphabusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReceptionchassisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptionchassisRepository extends EntityRepository
{
}
