<?php

namespace My\AlphabusBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * test2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class test2Repository extends EntityRepository
{
}
